language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

script:
  - bundle exec rubocop
  - bundle exec rspec
  - rake install
  - colorls
  - colorls -a
  - colorls -d
  - colorls -f
  - colorls -sd
  - colorls -sf
  - colorls -1
  - colorls -r
  - colorls -l

install:
  - gem install bundler
  - bundle install
