language:
  ruby

cache:
  bundler

rvm:
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'

script:
  - bundle exec rubocop
  - bundle exec rake spec
  - bundle exec rake install
  - bundle binstubs colorls
  - PATH=$PWD/bin:$PATH
  - colorls
  - colorls -1
  - colorls -a
  - colorls -A
  - colorls -d
  - colorls -f
  - colorls -l
  - colorls -l spec/fixtures/symlinks
  - ( cd spec/fixtures ; colorls .hidden-file ) | fgrep '.hidden-file'
  - colorls -l README.md
  - colorls -r
  - colorls --sd
  - colorls --sf
  - colorls --hyperlink
  - colorls -t
  - colorls --sort=time
  - colorls -U
  - colorls --sort=none
  - colorls -S
  - colorls --sort=size
  - colorls -h
  - colorls --gs
  - colorls spec/fixtures/symlinks
  - colorls README.md
  - colorls *
  - colorls | grep /
  - colorls --color
  - colorls --color=auto
  - colorls --color=never
  - colorls --color=always

