conditions: v1

if: branch = master OR tag IS present

language:
  ruby

os:
  - linux

cache: bundler

rvm:
  - '2.5'
  - '2.6'
  - '2.7'
  - 'truffleruby-head'

jobs:
  fast_finish: true

  allow_failures:
    - rvm: truffleruby-head

  include:
    - os: osx
      rvm: '2.7'

    - os: windows
      language: bash
      before_cache:
        - |-
          # https://unix.stackexchange.com/a/137322/107554
          pacman --sync --clean --noconfirm
        - bundle clean
      before_install:
        - ruby --version
        - gem --version
        - |
          if [[ ! -f /C/tools/msys64/--msys2-- ]]; then
             rm -rf /C/tools/msys64
             choco uninstall -y mingw
             choco upgrade --no-progress -y msys2 --params /NoUpdate
             ridk.cmd install dev_tools
          fi
        - touch /C/tools/msys64/--msys2--
      install:
        - bundle config set path 'vendor/bundle'
        - bundle install --retry=3
        - export MSYS=winsymlinks:nativestrict
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - /C/tools/msys64
          - vendor/bundle

before_install:
  - gem --version
  - gem install bundler -v '~> 2'

script:
  - bundle exec rubocop
  - bundle exec rake spec
  - bundle exec rake install
  - bundle binstubs colorls
  - PATH=$PWD/bin:$PATH
  - colorls
  - colorls -1
  - colorls -a
  - colorls -A
  - colorls -d
  - colorls -f
  - colorls -l
  - colorls -l spec/fixtures/symlinks
  - ( cd spec/fixtures ; colorls .hidden-file ) | fgrep '.hidden-file'
  - colorls -l README.md
  - colorls -r
  - colorls --sd
  - colorls --sf
  - colorls --hyperlink
  - colorls -t
  - colorls --sort=time
  - colorls -U
  - colorls --sort=none
  - colorls -S
  - colorls --sort=size
  - colorls -h
  - colorls --gs
  - colorls spec/fixtures/symlinks
  - colorls README.md
  - colorls *
  - colorls | grep /
  - colorls --color
  - colorls --color=auto
  - colorls --color=never
  - colorls --color=always
  - colorls --tree spec
  - colorls --tree=1
  - LC_ALL=C colorls spec/fixtures/
  - LC_ALL=C colorls --git spec/fixtures/
  - |
    if colorls does-not-exist; then
      echo "expected error!"
      exit 1
    else
      ret=$?
      if [ $ret -ne 2 ]; then
        echo "unexpected error: $ret"
        exit 1
      fi
    fi

deploy:
  provider: rubygems
  api_key:
    secure: iHo85pvy3iIp0/r8mbP0q0VPCFyYcwaQb19YUxwIGbMrksswIJPe2bsdAQTvd1fU3U+uwAgyzfaLMWgY6T1evVjv5GGXW0zmNthgWuaCbTBmzx3q6OPV6zJLsinKSJ4xbKjmTOi6BIhXTtc09dRRNp1d9U8HtmM9KyvD5ORm5M9W0/WxP3+8oOe0/yl3DOVNgCQ0j64KEqowLlfdJXe2q5iSUkZEvf+o5F6pz0g7dFiVHPVpJbZ9sOchPzYNMjLCx4jPt42J806oAH7TMeRC4lFpKgJr9U05LRGb22jiokHH6gl17RpuGRYJIexWkf3jb5iy9bivT2S2fGo9/BBKO5BvQAaL7McCwpdKM2QEyVy7RVbUz5D8vfXkJNIJankQj3Ikuz7qYyDglucGCpSGjecNCqL61NoBag7ORJ0RMWg7zklKjR59zeT4oks8rByx688y5Oi4f9Z98SPfc9NIJbHxbrDHtr13gm509cEXxwOLuVePa9J+mDGq2Uawi/PuIon1x2ztHUgvTx0DSYtwv96HzXet8QqXHwRKKjddxEApvCvGvaJV3akeUVjcsyei892ajHP6CffaKazPtogotfsu68g8WmKFWHFRkdmS6NIqg7MrnMRCjDkxAoQYYzt6cl95aBk4G7CTbjtXgIct1LGMM/WjE6K/jpeF0YLsVR4=
  gem: colorls
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master || $TRAVIS_TAG =~ ^v[0-9][.]
    repo: athityakumar/colorls
    rvm: '2.6'
    os: linux
